### ISSUE TITLE
Update the docs and the examples

### ISSUE THREAD

**Issue by iamcsharper** [NSSTC/sim-ecs#32]
Cloned version: 0.3.0
Issue: can't build the examples due to dramatic changes in API 
it looks like you got rid of Query, WithTag, and even commands in actions. A brief look into the code didn't give me answers so please, update your piece of great work!

**Comment by minecrawler** [comment]
Hi @iamcsharper , thank you for your interest and feedback! It seems you are using the 0.3.0 code while using the docs from the master branch. They are not compatible, because I developed a lot of new features for the upcoming 0.4.0 version (like commands, Query, etc.).

If you want to use 0.3.0, I recommend using the 0.3.0 docs, or use master and the master docs.

- You can find the code (including examples) and README for **0.3.0** [here](https://github.com/NSSTC/sim-ecs/tree/0.3.0) and 
- the code (including examples) and README for **master** [here](https://github.com/NSSTC/sim-ecs/tree/master).

The Github page hosts the docs for the master branch (it is labelled as 0.4.0 😉 ), and unfortunately I just recently started building them, so there is no rendered html docs for 0.3.0.

Does this help you?
